(function () {
  "use strict";

  function article(base) {
    return {
      roles: ["all"],
      readMinutes: 3,
      related: [],
      keywords: [],
      aliases: [],
      introducedIn: "1.0.0",
      updatedAt: "2026-07-11",
      ...base,
    };
  }

  const CATEGORIES = [
    { id: "start-here", title: "Start Here", description: "First-time setup, projector selection, and initial testing.", icon: "start-here" },
    { id: "worship-service", title: "Run a Worship Service", description: "Build, preview, and run a complete Sabbath service.", icon: "worship-service" },
    { id: "bible", title: "Bible Projection", description: "Search, preview, and project scripture on projector and OBS.", icon: "bible" },
    { id: "hymns", title: "Hymns and Languages", description: "Hymn index, search, languages, stanzas, and chorus return.", icon: "hymns" },
    { id: "obs", title: "OBS and Livestream", description: "WebSocket, Browser Sources, scenes, streaming, and Virtual Camera.", icon: "obs" },
    { id: "media", title: "Videos and Media", description: "Audio, video, practice mode, and media output options.", icon: "media" },
    { id: "shortcuts", title: "Keyboard Shortcuts", description: "Operator shortcuts for live worship and emergency actions.", icon: "shortcuts" },
    { id: "troubleshooting", title: "Troubleshooting", description: "Fix common projector, hymn, Bible, OBS, and media problems.", icon: "troubleshooting" },
    { id: "emergency", title: "Emergency Help", description: "Large-button recovery tools for use during a live service.", icon: "emergency" },
    { id: "training", title: "Training Mode", description: "Safe practice lessons without affecting live outputs.", icon: "training" },
    { id: "backup", title: "Backup and Restore", description: "Manual backup, autosave, and moving to another computer.", icon: "backup" },
    { id: "about", title: "About and Updates", description: "Version, release notes, licences, and support information.", icon: "about" },
  ];

  const TROUBLE_ITEMS = [
    ["projector-nothing", "Nothing appears on the projector", "Output not opened or wrong monitor", ["Open Presenter → Open Projector Screen", "Confirm external display is connected", "Use Emergency → Restart projector output"]],
    ["projector-wrong-monitor", "Wrong monitor is displaying content", "Projector window opened on primary display", ["Disconnect and reconnect projector cable", "Re-open projector from Presenter dashboard", "Drag projector window to external display if windowed"]],
    ["projector-frozen", "Projector output is frozen", "Presenter paused or display stuck", ["Press P to resume if paused", "Press C to clear emergency overlay", "Restart projector output from Emergency Help"]],
    ["projector-black", "Projector is black", "Blackout or emergency black active", ["Press C or Clear to return to lyrics", "Check presenter is active with a hymn selected", "Confirm emergency black is not active"], ["projector blank", "blank projector"]],
    ["text-too-small", "Text is too small", "Font scale too low in settings", ["Increase font scale in Settings", "Use full-screen hymn layout on projector", "Adjust OBS Browser Source font in overlay settings"]],
    ["text-cut-off", "Text is cut off", "Long verse or too many lines", ["Split long passages into smaller ranges", "Reduce max lines in OBS overlay layout", "Use full-screen scripture layout"]],
    ["obs-disconnected", "OBS is disconnected", "OBS closed or WebSocket disabled", ["Open OBS Studio", "Enable WebSocket on port 4455", "Reconnect in Settings → OBS Studio"]],
    ["obs-auth-failed", "OBS authentication failed", "Incorrect WebSocket password", ["Re-enter password in OBS settings panel", "Match password in OBS WebSocket settings", "Test connection before saving"]],
    ["obs-browser-blank", "OBS Browser Source is blank", "Wrong URL or server not running", ["Copy URL from OBS settings (desktop app)", "Set Browser Source to 1920×1080 with transparency", "Confirm presenter is Live for hymn/scripture updates"]],
    ["obs-source-missing", "OBS source is missing", "Scene item renamed or deleted", ["Refresh source list in OBS settings", "Re-map source to current scene item", "Use warning messages in mapping panel"]],
    ["vcam-unavailable", "Virtual Camera is unavailable", "OBS version or platform limitation", ["Update OBS Studio", "Start Virtual Camera from OBS first", "Use OBS Controls in worship app when connected"]],
    ["video-no-play", "Video does not play", "Missing file or unsupported format", ["Confirm file exists in media folder", "Use MP3/MIDI for audio practice mode", "Re-import media if path changed"]],
    ["backup-failed", "Backup failed", "Storage full or permission denied", ["Free disk space", "Export smaller component backup", "Retry from Settings → Backup & Restore"]],
  ];

  const ARTICLES = [
    article({
      id: "welcome-setup",
      category: "start-here",
      title: "Welcome and first-time setup",
      description: "Install, open the app, and prepare your first worship environment.",
      keywords: ["setup", "install", "first time", "start"],
      aliases: ["getting started", "new church"],
      readMinutes: 6,
      whatItDoes: "Gets Christ in Song ready for your first Sabbath service on this computer.",
      whenToUse: "Before your first service or when setting up a new operator machine.",
      howToUse: [
        "Open the desktop app or install the PWA for offline use.",
        "Select your default hymn language from the top bar.",
        "Open Settings to confirm language packs are ready.",
        "Open Presenter and test Open Projector Screen on the correct monitor.",
        "Complete the interactive setup checklist in this section.",
      ],
      workflow: "Install → Select language → Test projector → Build first service → Present",
      notes: ["The app works fully offline after first load.", "OBS is optional for congregation projector output."],
      mistakes: ["Skipping projector test before Sabbath morning.", "Not saving worship builder order before service."],
      related: ["setup-checklist", "projector-setup", "first-service"],
      route: "settings",
    }),
    article({
      id: "setup-checklist",
      category: "start-here",
      title: "Interactive setup checklist",
      description: "Track first-time setup tasks with saved progress.",
      keywords: ["checklist", "setup progress"],
      readMinutes: 4,
      whatItDoes: "Provides a saved checklist linking directly to settings and modules.",
      whenToUse: "During initial church setup or training a new operator.",
      howToUse: ["Open this article and use the checklist below.", "Check items only after completing the real task.", "Use Reset to start over for a new venue."],
      notes: ["Progress is stored locally on this device."],
      related: ["welcome-setup", "obs-connect"],
      checklistId: "setup",
    }),
    article({
      id: "projector-setup",
      category: "start-here",
      title: "Select the projector monitor",
      description: "Send congregation output to the correct display.",
      keywords: ["projector", "monitor", "display", "dual screen"],
      aliases: ["wrong monitor", "external display"],
      whatItDoes: "Opens the Electron projector window on an external display when available.",
      whenToUse: "When setting up dual-monitor worship for the first time.",
      howToUse: [
        "Connect the projector or congregation display.",
        "Go to Presenter → Open Projector Screen.",
        "If windowed, drag the projector window to the external monitor.",
        "Use fullscreen on the projector display.",
      ],
      related: ["projector-nothing", "presenter-live"],
      route: "presenter",
      routeCommand: "presenter-open-output",
    }),
    article({
      id: "first-service",
      category: "start-here",
      title: "Create your first worship service",
      description: "Build a simple service plan and test Preview and Live.",
      keywords: ["first service", "worship builder", "service plan"],
      howToUse: [
        "Open Worship Builder.",
        "Assign hymns to Opening, Prayer, and Closing slots.",
        "Add scripture or announcement items with Add Content.",
        "Save by staying on this device — plan auto-saves to local storage.",
        "Open Presenter → Present Current to go Live.",
      ],
      workflow: "Worship Builder → Assign hymns → Presenter → Present Current → Next slide",
      related: ["worship-build-plan", "preview-live"],
      route: "builder",
    }),
    article({
      id: "worship-build-plan",
      category: "worship-service",
      title: "Create a new service plan",
      description: "Use Worship Builder to order hymns, scripture, and announcements.",
      keywords: ["service plan", "worship builder", "order of service"],
      aliases: ["add hymn to service", "build service"],
      whatItDoes: "Stores your Sabbath order with drag-and-drop slots.",
      whenToUse: "During weekly service preparation.",
      howToUse: [
        "Open Worship Builder from the sidebar.",
        "Drag slots to reorder Opening Hymn, Scripture, Offering, and more.",
        "Click a slot to assign a hymn or add custom content.",
        "Use Add Content for scripture, prayers, announcements, and sermon title.",
      ],
      workflow: "Create Service → Add Welcome → Opening Hymn → Bible Reading → Announcements → Sermon → Closing Hymn",
      related: ["worship-live-run", "preview-live"],
      route: "builder",
    }),
    article({
      id: "preview-live",
      category: "worship-service",
      title: "Worship Preview and Worship Live",
      description: "Understand when projector and OBS update.",
      keywords: ["preview", "live", "send live", "presenter"],
      aliases: ["how do I show a verse", "go live"],
      whatItDoes: "Separates operator review from audience output.",
      whenToUse: "Before every service and when training new operators.",
      howToUse: [
        "Worship Preview: review next slide/hymn in operator panels before going live.",
        "Worship Live: audience sees content when Presenter session is active.",
        "Start Presenter with Present Current or Present from a hymn.",
        "Use Next/Previous only while Live to advance slides.",
      ],
      notes: [
        "OBS Browser Sources update when Presenter is Live (active, not paused).",
        "Editing Worship Builder does not change Live output until you present that item.",
      ],
      related: ["obs-preview-program", "presenter-live"],
    }),
    article({
      id: "worship-live-run",
      category: "worship-service",
      title: "Run the service live",
      description: "Operate slides, timer, clear, logo, and blackout during worship.",
      keywords: ["run service", "live worship", "next slide", "presenter"],
      howToUse: [
        "Open Presenter dashboard before service starts.",
        "Click Present Current to begin with the first assigned item.",
        "Use Next › or arrow keys to advance slides.",
        "Use emergency toolbar: Black (B), White (W), Logo (L), Clear (C).",
        "Pause (P) freezes audience display without closing presenter.",
      ],
      shortcut: "Arrow Right = Next · Arrow Left = Previous · C = Clear · B = Blackout",
      related: ["clear-vs-blackout", "emergency-help"],
      route: "presenter",
    }),
    article({
      id: "bible-search-reference",
      category: "bible",
      title: "Search by Bible reference",
      description: "Find verses using references like John 3:16 or Ps 23.",
      keywords: ["bible", "john 3:16", "reference", "verse", "scripture"],
      aliases: ["jn 3:16", "show verse", "import bible"],
      whatItDoes: "Loads KJV, ASV, and WEB translations from local JSON files.",
      whenToUse: "When projecting scripture during the sermon or scripture reading.",
      howToUse: [
        "Open Bible reader when available in navigation.",
        "Type a reference in the jump field (e.g. John 3:16, Romans 8:28).",
        "Select translation: KJV, ASV, or WEB.",
        "Add scripture slots in Worship Builder for planned readings.",
        "Send Live via Presenter when scripture is in the service queue.",
      ],
      examples: ["John 3:16", "John 3:16–18", "Psalm 23", "Revelation 14:6–12"],
      related: ["bible-obs-overlay", "scripture-clear"],
    }),
    article({
      id: "bible-obs-overlay",
      category: "bible",
      title: "Show verses on projector and OBS",
      description: "Use different layouts for congregation and livestream.",
      keywords: ["bible obs", "scripture overlay", "lower third"],
      aliases: ["show verse while preacher speaking", "verse over camera"],
      howToUse: [
        "Projector: use full-screen scripture in presenter or worship builder slot.",
        "OBS: add Scripture Browser Source URL from Settings → OBS Studio.",
        "Map Camera + Scripture scene in OBS scene mapping.",
        "Set default output to Projector + OBS in OBS settings.",
      ],
      related: ["obs-browser-sources", "obs-preview-program"],
    }),
    article({
      id: "hymn-search",
      category: "hymns",
      title: "Search hymns by number, title, or lyrics",
      description: "Find hymns quickly across loaded language packs.",
      keywords: ["hymn search", "hymn number", "title", "lyrics", "add hymn"],
      aliases: ["add a hymn", "find hymn"],
      howToUse: [
        "Open Search from the sidebar.",
        "Search by number, title, verse text, or chorus.",
        "Filter by category tags if needed.",
        "Open a hymn and use Add to Worship Builder.",
      ],
      related: ["hymn-live", "language-packs"],
      route: "search",
    }),
    article({
      id: "hymn-live",
      category: "hymns",
      title: "Send hymn lyrics Live",
      description: "Project stanzas and chorus with automatic chorus return.",
      keywords: ["hymn live", "stanza", "chorus", "lyrics"],
      howToUse: [
        "Open a hymn or assign it in Worship Builder.",
        "Start Presenter to go Live.",
        "Use Next to advance stanzas; chorus slides follow hymn data.",
        "OBS hymn overlay updates when Presenter is Live.",
      ],
      related: ["preview-live", "obs-browser-sources"],
      route: "presenter",
    }),
    article({
      id: "language-packs",
      category: "hymns",
      title: "Add hymn languages and import packs",
      description: "Manage built-in hymnals, import packs, and safely delete imported collections.",
      keywords: ["language", "import hymn pack", "add language", "delete hymnal", "hymnal library"],
      howToUse: [
        "Open Settings → Hymnal Library Manager.",
        "Import JSON or pack files; assign them to a hymn book and edition.",
        "Switch hymn book and language edition from the top bar or hymn index.",
        "Imported and user-created hymnals can be exported or deleted; built-in hymnals are protected.",
        "Deletion shows a reference-impact summary before removing favourites, builders, or history links.",
      ],
      related: ["backup-restore-guide"],
      route: "settings",
    }),
    article({
      id: "obs-connect",
      category: "obs",
      title: "Connect OBS WebSocket",
      description: "Link the worship app to OBS Studio on port 4455.",
      keywords: ["obs", "websocket", "connect", "password", "4455"],
      aliases: ["obs disconnected", "obs is disconnected", "enable obs websocket"],
      whatItDoes: "Connects via OBS WebSocket 5.x with encrypted password storage.",
      whenToUse: "Before livestreaming or using OBS Browser Source overlays.",
      howToUse: [
        "In OBS: Tools → WebSocket Server Settings → Enable, set password.",
        "In app: Settings → OBS Studio → Enable integration.",
        "Host 127.0.0.1, port 4455, enter password.",
        "Click Test Connection, then Save Settings.",
      ],
      related: ["obs-browser-sources", "obs-scene-mapping"],
      route: "settings",
      routeCommand: "open-obs-settings",
    }),
    article({
      id: "obs-browser-sources",
      category: "obs",
      title: "Add OBS Browser Sources",
      description: "Copy localhost URLs for scripture, hymn, and lower-third overlays.",
      keywords: ["browser source", "obs overlay", "url", "1920", "transparency"],
      aliases: ["browser source is blank", "reload browser source"],
      howToUse: [
        "Connect OBS and open Settings → OBS Studio.",
        "Copy each Browser Source URL (desktop app serves on localhost).",
        "In OBS add Browser Source, paste URL, set 1920×1080.",
        "Enable transparency for overlay sources.",
      ],
      notes: ["Browser Source server requires the desktop (Electron) app."],
      related: ["obs-connect", "bible-obs-overlay"],
    }),
    article({
      id: "obs-scene-mapping",
      category: "obs",
      title: "Map OBS scenes and sources",
      description: "Assign worship functions to your existing OBS scenes.",
      keywords: ["scene mapping", "source mapping", "camera scripture"],
      howToUse: [
        "Connect OBS, click Refresh Scenes and Refresh Sources.",
        "Map Live Camera, Scripture, Hymn, Lower Third, etc.",
        "Select source and the scene containing each Browser Source.",
        "Save Mappings — warnings appear if scenes are missing.",
      ],
      related: ["obs-preview-program", "obs-stream-record"],
    }),
    article({
      id: "obs-preview-program",
      category: "obs",
      title: "Worship Preview/Live vs OBS Preview/Program",
      description: "Avoid confusing worship state with OBS Studio Mode.",
      keywords: ["obs preview", "obs program", "studio mode", "worship preview"],
      diagram: "Christ in Song → Projector / Stage / OBS Browser Source → OBS Studio → Stream/Record/Virtual Camera",
      howToUse: [
        "Worship Preview: operator review before audience sees content.",
        "Worship Live: presenter active — updates projector and OBS overlays.",
        "OBS Preview Scene: next scene in OBS Studio Mode only.",
        "OBS Program Scene: what viewers see on stream/recording.",
      ],
      related: ["preview-live", "obs-scene-mapping"],
    }),
    article({
      id: "obs-stream-record",
      category: "obs",
      title: "Streaming, recording, and Virtual Camera",
      description: "Control OBS outputs from the worship app with confirmations.",
      keywords: ["stream", "record", "virtual camera", "zoom", "teams"],
      aliases: ["start virtual camera", "obs virtual camera zoom"],
      howToUse: [
        "Open OBS Controls in Settings or Presenter sidebar.",
        "Start Stream / Stop Stream (confirmation required by default).",
        "Start Record / Stop Record with status sync from OBS.",
        "Start Virtual Camera for Zoom or Microsoft Teams.",
      ],
      notes: ["Clear and Blackout do not stop streaming or recording."],
      related: ["obs-connect", "clear-vs-blackout"],
    }),
    article({
      id: "media-audio-practice",
      category: "media",
      title: "Hymn audio and practice mode",
      description: "Play MP3/MIDI attachments and practice without projecting.",
      keywords: ["audio", "mp3", "midi", "practice mode", "video", "media"],
      aliases: ["play a video", "video does not play"],
      howToUse: [
        "Open a hymn with attached audio in the song view.",
        "Use Play/Pause on the audio panel.",
        "Toggle Practice Mode to rehearse without changing presenter output.",
        "Upload audio per hymn where supported in song audio settings.",
      ],
      related: ["hymn-live"],
      route: "song",
    }),
    article({
      id: "clear-vs-blackout",
      category: "shortcuts",
      title: "Clear versus Blackout",
      description: "Know the difference between Clear, Logo, and Black emergency actions.",
      keywords: ["clear", "blackout", "logo", "emergency"],
      aliases: ["clear versus blackout", "does blackout stop streaming"],
      whatItDoes: "Clear returns to lyrics; Black shows black screen; Logo shows holding graphic.",
      notes: [
        "Blackout does not stop OBS streaming or recording.",
        "Clear worship overlays hides scripture/hymn OBS sources only.",
      ],
      shortcut: "C = Clear · B = Black · L = Logo",
      related: ["emergency-help", "worship-live-run"],
    }),
    article({
      id: "keyboard-shortcuts-reference",
      category: "shortcuts",
      title: "Keyboard shortcuts reference",
      description: "All presenter and emergency shortcuts in one table.",
      keywords: ["keyboard", "shortcut", "hotkey"],
      readMinutes: 5,
      shortcuts: [
        { keys: "→ / Page Down / Space", action: "Next slide", scope: "presenter" },
        { keys: "← / Page Up", action: "Previous slide", scope: "presenter" },
        { keys: "C", action: "Clear emergency / return to lyrics", scope: "emergency" },
        { keys: "B", action: "Black screen", scope: "emergency" },
        { keys: "W", action: "White screen", scope: "emergency" },
        { keys: "L", action: "Logo screen", scope: "emergency" },
        { keys: "P", action: "Pause / resume display", scope: "presenter" },
        { keys: "F", action: "Fullscreen output", scope: "presenter" },
        { keys: "Esc", action: "Close presenter / exit emergency", scope: "global" },
        { keys: "→ / ←", action: "Move slide in hymn view", scope: "hymns" },
      ],
      notes: ["Shortcuts do not run while typing in a text field."],
    }),
    article({
      id: "emergency-help",
      category: "emergency",
      title: "Using Emergency Help during live worship",
      description: "Large recovery buttons for projector, OBS, and overlay issues mid-service.",
      keywords: ["emergency", "blackout", "clear", "logo", "recovery"],
      aliases: ["live service recovery", "something went wrong"],
      whatItDoes: "Provides one-click recovery actions wired to real presenter and OBS commands.",
      whenToUse: "When the projector is blank, frozen, or OBS overlays need clearing during worship.",
      howToUse: [
        "Open Help Centre → Emergency Help (or use Emergency Help on Presenter dashboard).",
        "Use Clear to return to lyrics without stopping stream or recording.",
        "Use Blackout only when you need a black screen — confirm before activating.",
        "Use Reconnect OBS if the status badge shows disconnected.",
        "Open Diagnostics or copy a report if you need to escalate to technical support.",
      ],
      notes: [
        "Emergency actions do not stop OBS streaming or recording.",
        "Destructive actions ask for confirmation before running.",
      ],
      related: ["clear-vs-blackout", "obs-disconnected", "projector-black"],
      route: "help",
      routeCommand: "help-open-emergency",
    }),
    article({
      id: "training-overview",
      category: "training",
      title: "Training Mode overview",
      description: "Practice operator workflows without starting streams or affecting live output.",
      keywords: ["training", "practice", "lesson", "new operator"],
      whatItDoes: "Enables a training banner and lesson tracking; live streaming is never started from training.",
      whenToUse: "When onboarding a new worship operator or rehearsing before Sabbath.",
      howToUse: [
        "Open Help Centre → Training Mode.",
        "Click Enter Training Mode — a banner confirms training is active.",
        "Complete lessons at your own pace; mark complete when finished.",
        "Exit Training Mode before the live service.",
      ],
      notes: ["Projector output only changes if you explicitly present during training."],
      related: ["preview-live", "welcome-setup"],
    }),
    article({
      id: "backup-restore-guide",
      category: "backup",
      title: "Backup and restore your worship data",
      description: "Export .csbackup archives and restore on another computer.",
      keywords: ["backup", "restore", "export", "import", "autosave"],
      aliases: ["back up app", "restore a service", "where are backups stored"],
      howToUse: [
        "Settings → Backup & Restore → Export Backup.",
        "Choose full or component backup.",
        "Daily autosaves are kept on this device (see backup list).",
        "Restore merges or replaces worship plans, favorites, tags, and settings.",
        "OBS password is not exported — re-enter after restore.",
      ],
      roles: ["all", "admin"],
      related: ["obs-connect"],
      route: "settings",
      routeCommand: "export-backup",
    }),
    article({
      id: "diagnostics-overview",
      category: "troubleshooting",
      title: "System diagnostics and status",
      description: "Check projector, OBS, Bible, hymn, and backup health.",
      keywords: ["diagnostics", "status", "copy report"],
      route: "help",
      routeCommand: "help-open-diagnostics",
      related: ["obs-disconnected", "projector-nothing"],
    }),
    article({
      id: "pre-service-checklist",
      category: "start-here",
      title: "Pre-service checklist",
      description: "Interactive checklist for Sabbath morning readiness.",
      keywords: ["pre-service", "checklist", "sabbath morning"],
      checklistId: "pre-service",
      related: ["setup-checklist", "obs-connect"],
    }),
    article({
      id: "about-app",
      category: "about",
      title: "About Christ in Song Worship App",
      description: "Version, licences, and what's new.",
      keywords: ["about", "version", "updates", "licence"],
      related: ["backup-restore-guide"],
    }),
  ];

  TROUBLE_ITEMS.forEach((entry) => {
    const [id, title, cause, steps, extraAliases] = entry;
    ARTICLES.push(article({
      id,
      category: "troubleshooting",
      title,
      description: cause,
      keywords: [title.toLowerCase(), cause.toLowerCase()],
      aliases: extraAliases || [],
      troubleshooting: [{
        problem: title,
        cause,
        fix: steps.join(" "),
        prevent: "Complete pre-service checklist before worship.",
        steps,
      }],
      related: ["diagnostics-overview"],
    }));
  });

  const GLOSSARY = [
    { term: "Preview", definition: "Operator review state before audience output goes Live.", articleId: "preview-live" },
    { term: "Live", definition: "Active presenter session when congregation and OBS receive content.", articleId: "preview-live" },
    { term: "OBS Preview", definition: "Next scene in OBS Studio Mode — not the same as Worship Preview.", articleId: "obs-preview-program" },
    { term: "OBS Program", definition: "Current scene viewers see on stream or recording.", articleId: "obs-preview-program" },
    { term: "Browser Source", definition: "OBS layer loading a localhost URL for transparent overlays.", articleId: "obs-browser-sources" },
    { term: "Lower third", definition: "Text band at bottom of screen for names, titles, or references.", articleId: "obs-browser-sources" },
    { term: "Virtual Camera", definition: "OBS output appearing as a webcam in Zoom or Teams.", articleId: "obs-stream-record" },
    { term: "Blackout", definition: "Shows black on selected outputs without stopping stream/record.", articleId: "clear-vs-blackout" },
    { term: "Clear", definition: "Removes overlays or returns from emergency to lyrics.", articleId: "clear-vs-blackout" },
    { term: "WebSocket", definition: "Protocol connecting the app to OBS on port 4455.", articleId: "obs-connect" },
    { term: "Stanza", definition: "One verse section of a hymn slide sequence.", articleId: "hymn-live" },
    { term: "Chorus", definition: "Refrain section; may auto-return per hymn structure.", articleId: "hymn-live" },
    { term: "Autosave", definition: "Automatic local saves of worship data and daily backups.", articleId: "backup-restore-guide" },
  ];

  const FAQS = [
    { q: "Can I use the app without OBS?", a: "Yes. Projector and hymn presentation work fully without OBS. Enable OBS only for livestream overlays, recording control, or Virtual Camera.", articleId: "obs-connect" },
    { q: "Can the projector and livestream show different content?", a: "Yes. Use Projector + OBS output and different overlay layouts — full-screen on projector, lower-third on OBS.", articleId: "bible-obs-overlay" },
    { q: "Can I add more Bible translations?", a: "KJV, ASV, and WEB are bundled. Additional translations require JSON files in the Bible data folder.", articleId: "bible-search-reference" },
    { q: "Can I use the app without internet?", a: "Yes. Hymns, Bible, help articles, and search all work offline after first load.", articleId: "welcome-setup" },
    { q: "Does Blackout stop streaming?", a: "No. Blackout affects selected worship outputs only; OBS streaming and recording continue.", articleId: "clear-vs-blackout" },
    { q: "Does Clear stop recording?", a: "No. Clear returns to lyrics or hides overlays without stopping OBS recording.", articleId: "clear-vs-blackout" },
    { q: "Can I use OBS Virtual Camera with Zoom?", a: "Yes. Start Virtual Camera in OBS or worship app OBS Controls, then select OBS Virtual Camera in Zoom.", articleId: "obs-stream-record" },
    { q: "Where are backups stored?", a: "Manual exports save where you choose. Automatic daily backups stay in local app storage on this device.", articleId: "backup-restore-guide" },
    { q: "What happens when OBS disconnects?", a: "Projector continues normally. OBS badge shows disconnected; auto-reconnect retries if enabled.", articleId: "obs-disconnected" },
    { q: "How do I make text larger?", a: "Increase font scale in Settings and adjust OBS overlay layout presets.", articleId: "text-too-small" },
    { q: "How do I fix a blank projector?", a: "Open projector output, clear emergency black, and confirm presenter is Live with content.", articleId: "projector-black" },
    { q: "How do I show a verse while the preacher is speaking?", a: "Use OBS Camera + Scripture scene with Scripture Browser Source lower-third layout.", articleId: "bible-obs-overlay" },
  ];

  const SETUP_CHECKLIST = [
    { key: "open-app", label: "Open the application", route: "home" },
    { key: "language", label: "Select default hymn language", route: "settings" },
    { key: "projector", label: "Test projector / external display", route: "presenter", command: "presenter-open-output" },
    { key: "builder", label: "Create first worship service plan", route: "builder" },
    { key: "present-test", label: "Test Presenter Preview and Live", route: "presenter", command: "present-current" },
    { key: "clear-test", label: "Test Clear, Logo, and Blackout", route: "help", command: "help-open-emergency" },
    { key: "bible", label: "Confirm Bible translations available", route: "help", article: "bible-search-reference" },
    { key: "obs", label: "Connect and test OBS (if livestreaming)", route: "settings", command: "open-obs-settings" },
    { key: "browser-src", label: "Test OBS Browser Sources", route: "settings", command: "open-obs-settings" },
    { key: "backup", label: "Create first manual backup", route: "settings", command: "export-backup" },
  ];

  const PRE_SERVICE_CHECKLIST = [
    { key: "projector", label: "Projector connected and tested", critical: true, route: "presenter", command: "presenter-open-output" },
    { key: "obs", label: "OBS connected", critical: false, route: "settings", command: "open-obs-settings" },
    { key: "browser", label: "Browser Sources connected", critical: false, route: "settings", command: "open-obs-settings" },
    { key: "bible", label: "Bible translations available", critical: true, article: "bible-search-reference" },
    { key: "hymns", label: "Hymn languages loaded", critical: true, route: "index" },
    { key: "plan", label: "Service plan saved in Worship Builder", critical: true, route: "builder" },
    { key: "video", label: "Videos and media tested", critical: false, article: "media-audio-practice" },
    { key: "audio", label: "Video/audio output tested", critical: false },
    { key: "record", label: "Recording storage available", critical: false, article: "obs-stream-record" },
    { key: "vcam", label: "Virtual Camera tested (if needed)", critical: false, article: "obs-stream-record" },
    { key: "backup", label: "Pre-service backup created", critical: false, command: "export-backup" },
    { key: "logo", label: "Emergency logo available", critical: false, command: "emergency-logo" },
    { key: "operator", label: "Backup operator assigned", critical: false },
  ];

  const TRAINING_LESSONS = [
    { id: "first-verse", title: "Display your first Bible verse", steps: ["Open Bible help article", "Practice reference John 3:16", "Simulate Send Live in training banner"] },
    { id: "first-hymn", title: "Display your first hymn", steps: ["Open hymn 001", "Start training presenter", "Advance one stanza"] },
    { id: "build-service", title: "Build a simple worship service", steps: ["Add opening hymn slot", "Add scripture slot", "Review order"] },
    { id: "connect-obs", title: "Connect OBS (simulated)", steps: ["Review OBS settings article", "Practice mapping scenes on paper", "No real stream started"] },
    { id: "preview-live", title: "Use Preview and Live", steps: ["Review Preview vs Live article", "Practice Present Current in training"] },
    { id: "emergency", title: "Use Emergency Help", steps: ["Open Emergency Help", "Practice Clear action", "Confirm stream not stopped"] },
  ];

  function getCategory(id) {
    return CATEGORIES.find((cat) => cat.id === id) || null;
  }

  function getArticle(id) {
    return ARTICLES.find((item) => item.id === id) || null;
  }

  function getArticlesByCategory(categoryId) {
    return ARTICLES.filter((item) => item.category === categoryId);
  }

  window.CISHelpContent = {
    CATEGORIES,
    ARTICLES,
    GLOSSARY,
    FAQS,
    SETUP_CHECKLIST,
    PRE_SERVICE_CHECKLIST,
    TRAINING_LESSONS,
    getCategory,
    getArticle,
    getArticlesByCategory,
  };
})();
